modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="ssoundreloader"
version="${file.jarVersion}"
displayName="Sound Reloader Mod"
authors="suppergerrie2"
description='''Adds the ability to reload the sound engine without reloading all other resources.'''